# Generated by Django 4.1.7 on 2023-02-20 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128)),
                ('img', models.ImageField(upload_to='')),
                ('ctg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('discription', models.CharField(max_length=512)),
                ('brand', models.CharField(max_length=128)),
                ('on_complect', models.CharField(max_length=128)),
                ('uzunlik', models.CharField(max_length=128)),
                ('kenglik', models.CharField(max_length=128)),
                ('balandlik', models.CharField(max_length=128)),
                ('subctg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subcategory')),
            ],
        ),
    ]
